spring:
  application:
    name: url_backend

  cache:
    jcache:
      config: classpath:ehcache.xml

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 500
        format_sql: true
    show-sql: true
    open-in-view: false

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration-time: ${JWT_EXPIRATION_TIME}

#test:
#  data:
#    enabled: true # 테스트 데이터 생성 기능 활성화
